spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: reservook@gmail.com
    password: xyqsscnawvcgbosd
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true